name: "Comment Run"
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  comment-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: ibnesayeed/actions-comment-run@cmnt-file
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-associations: '["OWNER"]'
