name: "Comment Run"
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  comment-run:
    # if: contains(github.event.issue_comment.comment.body, '@github-actions run')
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{ github.event.issue_comment }} there"
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: ibnesayeed/actions-comment-run@cmnt-file
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-associations: '["OWNER"]'
