name: Tagify

on:
  - push

jobs:
  tagify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: imgtagger
        run: |
          imgtags=$(echo "${{ github.ref }}" | sed 's/refs\/tags\//latest,/; s/refs\/heads\///')
          echo "::set-output name=commits::$imgtags"
      - run: |
          echo "TAGS: $${{ steps.imgtagger.outputs.imgtags }}"
